name: CI

on:
  pull_request:
    branches: [ DEV, QA, main ]
  push:
    branches: [ DEV, QA, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      #Descargar el c√≥digo
      - name: Checkout
        uses: actions/checkout@v4

      #JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      #Restaurar dependencias y compilar
      - name: Build with Maven
        run: mvn -B clean install

      #Ejecutar pruebas unitarias
      - name: Run tests
        run: mvn test

      #Publicar resultados de pruebas
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: target/surefire-reports/

      #Publicar logs de build
      - name: Upload build logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs
          path: target/*.log